Panggung Krapyak. Salah satu komponen dari kesatuan Sumbu Filosofi Yogyakarta, dan terletak paling selatan.
Memiliki beberapa kemungkinan fungsi. Secara simbolis (penanda paling selatan), secara rekeasi (menjadi tempat istirahat saat berburu), dan pertahanan (karena letaknya yang strategis dalam pemantauan).
Tempat mulainya narasi filosofi “Sangkaning Dumadi”. Perjalanan hidup manusia dari dalam kandungan sampai menikah.
Sang Pelindung: Hmm.. begitu yaaa hoooo...
Sang Pelindung: Jadi ini seperti benteng pertahanan selatan ya? Hohoho... 
Sang Pelindung: Selain itu juga tempat berburu karena sekelilingnya berupa hutan krapyak, dan banyak rusa sebagai terget. Hohoho
Sang Pelindung: Jadi pengen berburu aku ... 
Sang Pelindung: Ora ora ora, waktunya melanjutkan ke area selanjunya...
Sang Pelindung: Semangat diriku yang kecil ini.
